name: cursos
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flat_list: ^0.1.14
  provider: ^6.0.0
  page_view_dot_indicator: ^2.1.0
  toast: ^0.3.0
  flutter_share: ^2.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/recursos/imagens/flutter.png
    - lib/recursos/imagens/cursos1.png
    - lib/recursos/imagens/marketing-digital.png
    - lib/recursos/imagens/canva.png
    - lib/recursos/imagens/web.png
    - lib/recursos/imagens/edicao-video.png
    - lib/recursos/imagens/excel.png
    - lib/recursos/imagens/fotografia.png
    - lib/recursos/imagens/logoc.png
    - lib/recursos/imagens/python.jpg
    - lib/recursos/imagens/ifba-divulgao.jpg
    - lib/recursos/json/feed.json
    - lib/recursos/json/comentarios.json